server:
  port : 0
spring:
  application:
    name: product-service


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:9001/eureka